name: Java Maven CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up JDK
      - name: Set up JDK 21
        uses: actions/checkout@v4
        with:
          java-version: '21' # Adjust this to the JDK version your project requires
          distribution: 'temurin' # Choose the JDK distribution (temurin, zulu, etc.)
#          cache: 'maven'

      - name: Run test
        run: ./mvnw test