#name: Build Workflow
#
#on:
#  push:
#    branches:
#      - main
#
#permissions:
#  id-token: write
#  contents: read
#
#jobs:
#  dev:
#    uses: phu-ng/cicd-scripts/.github/workflows/build.yml@main
